import React from 'react'

const PARAMS = [
  { label: 'Round Number', desc: 'Unique identifier for each round' },
  { label: 'Server Key', desc: 'Random string generated by the server' },
  { label: 'Crash Point', desc: 'The multiplier where the round crashes' },
  { label: 'Provably Fair Hash', desc: 'SHA-512 hash of the combined data' },
]

const ProvablyFairParameters = () => (
  <>
    <div className="modal__frame__1">
      <h3 className="modal__subtitle">The Four Parameters:</h3>
      <span className="modal__frame__1__text">Every round uses these four elements:</span>
      <div className="modal__ol">
        {PARAMS.map((param, i) => (
          <div key={i} className="modal__ol__item">
            <span className="modal__ol__number">{i + 1}.</span>
            <p className="modal__list__label">{param.label} <span className="modal__list__desc"> – {param.desc}</span></p>
          </div>
        ))}
      </div>
    </div>

    <div className="modal__frame__1">
      <h3 className="modal__subtitle">Verification Formula</h3>
      <div className="modal__frame__content">
        <p className="modal__frame__1__text">Provably Fair Hash = SHA512(ServerKey + "." + CrashPoint + "." + RoundNumber)</p>
      </div>
    </div>

    <div className="modal__frame__1">
      <h3 className="modal__subtitle">Example</h3>
      <div className="modal__frame__content">
        <p className="modal__frame__1__text">SHA512("7k9mX2pQ4nR8wL3vB6hJ5tY.2.45.1") = 8f3a2b9c7d1e6f4a5b8c9d2e3f4a5b6c7d8e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a</p>
      </div>
    </div>
  </>
)

export default ProvablyFairParameters
