import React from 'react'
import DefaultModal from '../DefaultModal'

const ProvablyFairModal = ({ isOpen, onClose }) => {
  return (
    <DefaultModal isOpen={isOpen} onClose={onClose} className="modal--centered no-scrollbar" style={{ maxWidth: 1006, width: "100%", maxHeight: 581, overflowY: "auto", borderRadius: 16, padding: 24, border: '1px solid rgba(var(--line))' }}>
      <section className="provably__fair__modal__content">
        <h2 className="modal__title">Provably Fair</h2>

        <div className="modal__content">
          <div className="modal__instructions">
            <h3 className="modal__section__subtitle">How It Works</h3>
            <p className="modal__text">Our Provably Fair system uses several parameters to ensure complete transparency and fairness. Each round has both hidden and revealed states.</p>
          </div>

          <div className="modal__frame">
            <h3 className="modal__subtitle">Before the Round Starts (Hidden State)</h3>
            <div className="modal__frame__content">
              <div className="modal__frame__row--header">
                <span>Round Number</span>
                <span>Server Key</span>
                <span>Crash Point</span>
                <span>Provably Fair Hash</span>
              </div>
              <div className="modal__separator"></div>
              <div className="modal__frame__row--content">
                <span>1</span>
                <span>hidden</span>
                <span>Hidden</span>
                <span>8f3a2b9c7d1e…</span>
              </div>
            </div>
          </div>

          <div className="modal__frame__1">
            <span className="modal__frame__1__text">Before the game begins, players can see:</span>
            <ul>
              <li>
                <p className="modal__list__label">Round Number <span className="modal__list__desc"> – The current round identifier</span></p>
              </li>
              <li>
                <p className="modal__list__label">Provably Fair Hash <span className="modal__list__desc"> – A cryptographic hash that proves the round outcome was predetermined</span></p>
              </li>
            </ul>
            <span className="modal__frame__1__text">The Server Key and Crash Point remain hidden to ensure fairness.</span>
          </div>

          <div className="modal__frame">
            <h3 className="modal__subtitle">After the Round Ends (Revealed State)</h3>
            <div className="modal__frame__content">
              <div className="modal__frame__row--header">
                <span>Round Number</span>
                <span>Server Key</span>
                <span>Crash Point</span>
                <span>Provably Fair Hash</span>
              </div>
              <div className="modal__separator"></div>
              <div className="modal__frame__row--content">
                <span>1</span>
                <span>7k9mX2pQ4nR8wL…</span>
                <span>2.45x</span>
                <span>8f3a2b9c7d1e…</span>
              </div>
            </div>
          </div>

          <div className="modal__frame__1">
            <span className="modal__frame__1__text">Once the round completes, all parameters are revealed:</span>
            <ul>
              <li>
                <p className="modal__list__label">Server Key <span className="modal__list__desc"> – The random server-generated key</span></p>
              </li>
              <li>
                <p className="modal__list__label">Crash Point <span className="modal__list__desc"> – The multiplier where the round ended</span></p>
              </li>
              <li>
                <p className="modal__list__label">Provably Fair Hash <span className="modal__list__desc"> – Remains the same, proving nothing changed</span></p>
              </li>
            </ul>
            <span className="modal__frame__1__text">The Server Key and Crash Point remain hidden to ensure fairness.</span>
          </div>

            <div className="modal__frame__1">
            <h3 className="modal__subtitle">The Four Parameters:</h3>
            <span className="modal__frame__1__text">Every round uses these four elements:</span>
            <div className="modal__ol">
              <div className="modal__ol__item"><span className="modal__ol__number">1.</span><p className="modal__list__label">Round Number <span className="modal__list__desc"> – Unique identifier for each round</span></p></div>
              <div className="modal__ol__item"><span className="modal__ol__number">2.</span><p className="modal__list__label">Server Key <span className="modal__list__desc"> – Random string generated by the server</span></p></div>
              <div className="modal__ol__item"><span className="modal__ol__number">3.</span><p className="modal__list__label">Crash Point <span className="modal__list__desc"> – The multiplier where the round crashes</span></p></div>
              <div className="modal__ol__item"><span className="modal__ol__number">4.</span><p className="modal__list__label">Provably Fair Hash <span className="modal__list__desc"> – SHA-512 hash of the combined data</span></p></div>
            </div>
          </div>

          <div className="modal__frame__1">
            <h3 className="modal__subtitle">Verification Formula</h3>
            <div className="modal__frame__content">
              <p className="modal__frame__1__text">Provably Fair Hash = SHA512(ServerKey + "." + CrashPoint + "." + RoundNumber)</p>
            </div>
          </div>

          <div className="modal__frame__1">
            <h3 className="modal__subtitle">Example</h3>
            <div className="modal__frame__content">
              <p className="modal__frame__1__text">SHA512("7k9mX2pQ4nR8wL3vB6hJ5tY.2.45.1") = 8f3a2b9c7d1e6f4a5b8c9d2e3f4a5b6c7d8e9f1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9c0d1e2f3a</p>
            </div>
          </div>
        </div>
      </section>
    </DefaultModal>
  )
}

export default ProvablyFairModal